// app/privacy-policy/page.tsx
import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="prose prose-lg prose-gray dark:prose-invert">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">
          Privacy Policy
        </h1>
        <p className="text-gray-600 dark:text-gray-300">
          Last updated: May 17, 2025
        </p>

        <p className="mt-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>

        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{" "}
          <a
            href="https://www.termsfeed.com/privacy-policy-generator/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300">
            Privacy Policy Generator
          </a>
          .
        </p>

        <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold text-gray-900 dark:text-white mt-6 mb-2">
          Interpretation
        </h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-xl font-semibold text-gray-900 dark:text-white mt-6 mb-2">
          Definitions
        </h3>
        <p>For the purposes of this Privacy Policy:</p>

        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Application</strong> refers to Cerita Senja Cafe, the
            software program provided by the Company.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Cerita Senja Cafe.
          </li>
          <li>
            <strong>Country</strong> refers to: Indonesia
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Application.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        {/* Lanjutkan dengan bagian-bagian lainnya dengan pola yang sama */}
        {/* Saya akan menunjukkan beberapa bagian sebagai contoh */}

        <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-xl font-semibold text-gray-900 dark:text-white mt-6 mb-2">
          Types of Data Collected
        </h3>

        <h4 className="text-lg font-medium text-gray-900 dark:text-white mt-4 mb-2">
          Personal Data
        </h4>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>

        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        {/* ... (lanjutkan dengan bagian-bagian lainnya) */}

        <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">
          Contact Us
        </h2>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>

        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li>
            By email:{" "}
            <a
              href="mailto:zieqanw@outlook.com"
              className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300">
              zieqanw@outlook.com
            </a>
          </li>
          <li>
            By visiting this page on our website:{" "}
            <a
              href="https://ceritasenjacafe.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300">
              https://ceritasenjacafe.com
            </a>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
